### PR TITLE
:sparkles: Add `reqwest-async` backend

### LINKED ISSUE #1: [feature]: `reqwest` backend
### What's your idea?

I found this crate, and it seems like exactly what I need for my project. However, I currently do not pull in `ureq` in my project and I'd prefer not to do so. I would be willing to make a PR to add a `reqwest` feature if that's something you'd be interested in.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tazz4843**
As the title states, this commit adds a `reqwest-async` backend. It requires the `tokio` runtime, as it spawns an async background task.

Currently untested, needed to push to be able to test.

Closes #1

### CODE REVIEW

**Comment by tazz4843** [comment]
I have absolutely zero clue where the stable failure is coming from. As far as I can tell, the only place tokio is used as a dep is in the `dep:tokio` format.

**Comment by tazz4843** [comment]
Turns out the `dep:tokio` format was the source of the error.

**Comment by tazz4843** [comment]
Okay, so it turns out `<impl Log for Fenrir>::flush` never gets called. It has to be manually called by a user. Not sure what you think the best way of doing this would be. I could probably spawn a background async task that flushes logs as they're received, but that would only work in an async context.

**Comment by tazz4843** [comment]
I added a buffer that buffers logs until they reach a specified limit, configurable by the user.

**Comment by flying7eleven** [comment]
LGTM! Thanks a lot for your work on that topic!

**Pull request merged**
